### PR TITLE
Update gdbcontroller.py

### PR DESCRIPTION
**Pull request by matkuki**
Line 124 added: this fixes a crash on Windows, when calling the `exit` method.

- [] I have added an entry to `CHANGELOG.md`

## Test plan

Tested by running
```
# command(s) to exercise these changes
```

### CODE REVIEW

**Comment by cs01** [comment]
What version of gdbgui are you using? I didn’t think it worked on windows.

**Comment by matkuki** [comment]
`0.10.0.2`, installed with `pip install pygdbmi`.
Except for this error, it works without problems 👍

**Comment by matkuki** [comment]
Forgot to mention that I'm using it for debugging embedded systems, not desktop applications.

**Comment by barisione** [comment]
@matkuki Sorry for the delay! Your patch looks good.

Can you please add a changelog entry?
Looks at existing ones for inspiration and add it somewhere under `## 0.10.0.3`.

**Comment by cs01** [comment]
Agreed, looks good other than the changelog is missing an entry

**Comment by barisione** [comment]
I updated your patch (leaving you as author!) to add a changelog entry. I had to make a new PR so I could push my changes, see https://github.com/cs01/pygdbmi/pull/79.

**Pull request closed without merging**
